import type { ErrorTag } from '@/types/taxonomy'

export interface ListenRespondQuestion {
  id: string
  question: string          // Norwegian question (large T1 display)
  questionEnglish: string   // Translation shown as subtitle
  expectedKeywords: string[] // Words a valid answer should contain (normalised lowercase)
  hint: string              // Short English coaching tip
  conceptId: string         // Concept this question exposes — MUST exist in the level's graph
  errorTag: ErrorTag        // Tag used when the user's answer misses
  audioUrl?: string
}

const AUDIO_BASE = '/audio/sentences'

const A1_QUESTIONS: ListenRespondQuestion[] = [
  {
    id: 'morning',
    question: 'Hva gjør du om morgenen?',
    questionEnglish: 'What do you do in the morning?',
    expectedKeywords: ['stå', 'opp', 'kaffe', 'frokost', 'spiser', 'drikker', 'dusjer'],
    hint: 'Beskriv morgenrutinen din.',
    conceptId: 'present-tense-regular',
    errorTag: 'verb-tense',
    audioUrl: `${AUDIO_BASE}/morning.mp3`,
  },
  {
    id: 'where-live',
    question: 'Hvor bor du?',
    questionEnglish: 'Where do you live?',
    expectedKeywords: ['bor', 'hus', 'leilighet', 'by', 'oslo', 'norge'],
    hint: 'Si hvor du bor.',
    conceptId: 'question-formation',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/where-live.mp3`,
  },
  {
    id: 'breakfast',
    question: 'Hva spiser du til frokost?',
    questionEnglish: 'What do you eat for breakfast?',
    expectedKeywords: ['spiser', 'brød', 'egg', 'havregrøt', 'frukt', 'yoghurt', 'frokost'],
    hint: 'Nevn noe du spiser om morgenen.',
    conceptId: 'present-tense-regular',
    errorTag: 'verb-tense',
    audioUrl: `${AUDIO_BASE}/breakfast.mp3`,
  },
  {
    id: 'name',
    question: 'Hva heter du?',
    questionEnglish: 'What is your name?',
    expectedKeywords: ['heter', 'navn', 'jeg', 'er'],
    hint: 'Si navnet ditt.',
    conceptId: 'personal-pronouns',
    errorTag: 'pronoun-choice',
    audioUrl: `${AUDIO_BASE}/name.mp3`,
  },
  {
    id: 'how-are-you',
    question: 'Hvordan har du det?',
    questionEnglish: 'How are you?',
    expectedKeywords: ['bra', 'fint', 'ok', 'godt', 'takk', 'dårlig'],
    hint: 'Beskriv hvordan du har det.',
    conceptId: 'question-formation',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/how-are-you.mp3`,
  },
  {
    id: 'job',
    question: 'Hva jobber du med?',
    questionEnglish: 'What do you do for work?',
    expectedKeywords: ['jobber', 'student', 'lærer', 'lege', 'ingeniør', 'kontor', 'skole'],
    hint: 'Si hva du jobber med eller at du er student.',
    conceptId: 'common-prepositions',
    errorTag: 'preposition',
    audioUrl: `${AUDIO_BASE}/job.mp3`,
  },
  {
    id: 'hobby',
    question: 'Hva liker du å gjøre på fritiden?',
    questionEnglish: 'What do you like to do in your free time?',
    expectedKeywords: ['liker', 'lese', 'løpe', 'spille', 'se', 'film', 'musikk', 'trene'],
    hint: 'Nevn noe du liker å gjøre.',
    conceptId: 'infinitive-form',
    errorTag: 'verb-tense',
    audioUrl: `${AUDIO_BASE}/hobby.mp3`,
  },
  {
    id: 'weekend',
    question: 'Hva liker du å gjøre i helgen?',
    questionEnglish: 'What do you like to do on the weekend?',
    expectedKeywords: ['liker', 'helg', 'helgen', 'gjøre'],
    hint: 'Beskriv hva du gjør i helgen.',
    conceptId: 'basic-adjectives',
    errorTag: 'verb-tense',
    audioUrl: '',
  },
  // Batch 2 deepening (2026-06-28, linguist-reviewed; audio generated via edge-tts nb-NO-PernilleNeural).
  {
    id: 'a1-family',
    question: 'Hva heter foreldrene dine?',
    questionEnglish: "What are your parents' names?",
    expectedKeywords: ['faren', 'moren', 'min', 'heter', 'mor', 'far'],
    hint: 'Bruk eiendomsord (faren min, moren min).',
    conceptId: 'possessive-pronouns',
    errorTag: 'pronoun-choice',
    audioUrl: `${AUDIO_BASE}/a1-family.mp3`,
  },
  {
    id: 'a1-age',
    question: 'Hvor gammel er du?',
    questionEnglish: 'How old are you?',
    expectedKeywords: ['år', 'jeg', 'er', 'tjue', 'tretti'],
    hint: "Svar med 'Jeg er … år'.",
    conceptId: 'to-be-verb',
    errorTag: 'verb-conjugation',
    audioUrl: `${AUDIO_BASE}/a1-age.mp3`,
  },
  {
    id: 'a1-fruit',
    question: 'Vil du ha et eple eller en banan?',
    questionEnglish: 'Would you like an apple or a banana?',
    expectedKeywords: ['en', 'et', 'eple', 'banan', 'vil', 'ha'],
    hint: 'Velg riktig artikkel (et eple, en banan).',
    conceptId: 'noun-gender',
    errorTag: 'noun-gender',
    audioUrl: `${AUDIO_BASE}/a1-fruit.mp3`,
  },
  {
    id: 'a1-pet',
    question: 'Har du et kjæledyr?',
    questionEnglish: 'Do you have a pet?',
    expectedKeywords: ['hund', 'katt', 'en', 'ja', 'nei', 'har'],
    hint: 'Bruk en/et (en hund, en katt).',
    conceptId: 'indefinite-articles',
    errorTag: 'article-use',
    audioUrl: `${AUDIO_BASE}/a1-pet.mp3`,
  },
  {
    id: 'a1-good-friends',
    question: 'Har du gode venner i Norge?',
    questionEnglish: 'Do you have good friends in Norway?',
    expectedKeywords: ['ja', 'gode', 'mange', 'venner', 'har', 'hyggelige'],
    hint: 'Bruk adjektiv i flertall (gode venner).',
    conceptId: 'adjective-agreement',
    errorTag: 'adjective-agreement',
    audioUrl: `${AUDIO_BASE}/a1-good-friends.mp3`,
  },
  {
    id: 'a1-dislike-food',
    question: 'Hva liker du ikke å spise?',
    questionEnglish: "What don't you like to eat?",
    expectedKeywords: ['liker', 'ikke', 'fisk', 'kjøtt', 'grønnsaker'],
    hint: "Plasser 'ikke' riktig (Jeg liker ikke …).",
    conceptId: 'negation',
    errorTag: 'negation-placement',
    audioUrl: `${AUDIO_BASE}/a1-dislike-food.mp3`,
  },
  {
    id: 'a1-yesterday',
    question: 'Hva gjorde du i går?',
    questionEnglish: 'What did you do yesterday?',
    expectedKeywords: ['jobbet', 'spiste', 'var', 'gikk', 'handlet', 'så'],
    hint: 'Bruk fortid (jobbet, spiste, var).',
    conceptId: 'preterite-regular',
    errorTag: 'verb-tense',
    audioUrl: `${AUDIO_BASE}/a1-yesterday.mp3`,
  },
  {
    id: 'a1-can-english',
    question: 'Kan du snakke engelsk?',
    questionEnglish: 'Can you speak English?',
    expectedKeywords: ['ja', 'kan', 'litt', 'snakker', 'nei'],
    hint: 'Bruk modalverb (kan) + infinitiv.',
    conceptId: 'common-modal-verbs',
    errorTag: 'modal-verb',
    audioUrl: `${AUDIO_BASE}/a1-can-english.mp3`,
  },
]

const B1_QUESTIONS: ListenRespondQuestion[] = [
  {
    id: 'b1-past-experience',
    question: 'Fortell om noe du hadde gjort før du begynte å lære norsk.',
    questionEnglish: 'Tell me about something you had done before you started learning Norwegian.',
    expectedKeywords: ['hadde', 'lært', 'jobbet', 'studert', 'bodd', 'reist', 'snakket'],
    hint: 'Use "hadde + past participle" to describe a completed past action.',
    conceptId: 'past-perfect',
    errorTag: 'verb-tense',
    audioUrl: '',
  },
  {
    id: 'b1-opinion',
    question: 'Hva synes du er den vanskeligste delen av norsk grammatikk?',
    questionEnglish: 'What do you think is the hardest part of Norwegian grammar?',
    expectedKeywords: ['synes', 'tror', 'mener', 'vanskelig', 'grammatikk', 'ordstilling', 'verb'],
    hint: 'Give your opinion using "synes", "tror" or "mener".',
    conceptId: 'discourse-markers',
    errorTag: 'meaning-misunderstood',
    audioUrl: '',
  },
  {
    id: 'b1-wish',
    question: 'Hva skulle du ønske du kunne gjøre bedre på norsk?',
    questionEnglish: 'What do you wish you could do better in Norwegian?',
    expectedKeywords: ['skulle', 'ønske', 'kunne', 'snakke', 'skrive', 'forstå', 'lese'],
    hint: 'Use "skulle ønske jeg kunne..." to express a wish.',
    conceptId: 'subjunctive-equivalents',
    errorTag: 'modal-verb',
    audioUrl: '',
  },
  {
    id: 'b1-give-up',
    question: 'Har du noen gang gitt opp noe som var viktig for deg?',
    questionEnglish: 'Have you ever given up on something that was important to you?',
    expectedKeywords: ['gitt', 'opp', 'sluttet', 'prøvde', 'fortsatte', 'vanskelig', 'aldri'],
    hint: 'Use "gi opp" (to give up) and describe the situation.',
    conceptId: 'phrasal-verbs',
    errorTag: 'preposition',
    audioUrl: '',
  },
  {
    id: 'b1-formal-email',
    question: 'Hvordan ville du starte en formell e-post på norsk?',
    questionEnglish: 'How would you begin a formal email in Norwegian?',
    expectedKeywords: ['kjære', 'hei', 'viser', 'henvendelse', 'angående', 'skriver', 'hilsen'],
    hint: 'Think about formal opening phrases for written Norwegian.',
    conceptId: 'formal-informal-register',
    errorTag: 'wrong-word-same-category',
    audioUrl: '',
  },
  {
    id: 'b1-double-definite',
    question: 'Beskriv det flotteste stedet du har besøkt.',
    questionEnglish: 'Describe the most beautiful place you have visited.',
    expectedKeywords: ['den', 'det', 'de', 'store', 'vakre', 'flotte', 'beste', 'stedet'],
    hint: 'Use the double definite: "den vakre fjorden", "det store fjellet".',
    conceptId: 'double-definite',
    errorTag: 'adjective-agreement',
    audioUrl: '',
  },
  {
    id: 'b1-indirect-question',
    question: 'Vet du om det er mulig å lære seg norsk på ett år?',
    questionEnglish: 'Do you know whether it is possible to learn Norwegian in one year?',
    expectedKeywords: ['vet', 'lurer', 'om', 'mulig', 'tror', 'kanskje', 'år'],
    hint: 'Embed the yes/no question using "om": "Jeg lurer på om...".',
    conceptId: 'indirect-questions',
    errorTag: 'word-order',
    audioUrl: '',
  },
  {
    id: 'b1-idiom',
    question: 'Hva gjør du når du vil ta det med ro?',
    questionEnglish: 'What do you do when you want to take it easy?',
    expectedKeywords: ['ta', 'ro', 'slappe', 'av', 'hvile', 'lese', 'gå', 'tur'],
    hint: '"Ta det med ro" means to take it easy — describe what that looks like for you.',
    conceptId: 'idiomatic-expressions',
    errorTag: 'meaning-misunderstood',
    audioUrl: '',
  },
  // Batch 2 deepening (2026-06-28, linguist-reviewed; audio generated via edge-tts nb-NO-PernilleNeural).
  {
    id: 'b1-cleft-motivation',
    question: 'Hva er det som motiverer deg til å lære norsk?',
    questionEnglish: 'What is it that motivates you to learn Norwegian?',
    expectedKeywords: ['det', 'som', 'motiverer', 'jobb', 'familie', 'fordi'],
    hint: 'Bruk kløyvd setning (Det er … som …).',
    conceptId: 'cleft-sentences',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b1-cleft-motivation.mp3`,
  },
  {
    id: 'b1-passive-17mai',
    question: 'Hvordan feires 17. mai i Norge?',
    questionEnglish: 'How is the 17th of May celebrated in Norway?',
    expectedKeywords: ['feires', 'blir', 'feiret', 'med', 'tog', 'flagg'],
    hint: 'Bruk passiv (feires / blir feiret).',
    conceptId: 's-passive-vs-bli-passive',
    errorTag: 'verb-conjugation',
    audioUrl: `${AUDIO_BASE}/b1-passive-17mai.mp3`,
  },
  {
    id: 'b1-hard-decision',
    question: 'Fortell om en gang du måtte ta en vanskelig avgjørelse.',
    questionEnglish: 'Tell me about a time you had to make a difficult decision.',
    expectedKeywords: ['da', 'fordi', 'selv', 'om', 'måtte', 'valgte'],
    hint: 'Bruk leddsetninger (da …, fordi …, selv om …).',
    conceptId: 'complex-subordination',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b1-hard-decision.mp3`,
  },
  {
    id: 'b1-figure-out-words',
    question: 'Hvordan finner du ut av nye ord når du leser?',
    questionEnglish: 'How do you figure out new words when you read?',
    expectedKeywords: ['finner', 'ut', 'slår', 'opp', 'gjetter', 'spør'],
    hint: 'Bruk partikkelverb (finne ut av, slå opp).',
    conceptId: 'phrasal-verbs',
    errorTag: 'preposition',
    audioUrl: `${AUDIO_BASE}/b1-figure-out-words.mp3`,
  },
  {
    id: 'b1-city-pros-cons',
    question: 'Hva er fordelene og ulempene med å bo i en storby?',
    questionEnglish: 'What are the advantages and disadvantages of living in a big city?',
    expectedKeywords: ['på', 'den', 'ene', 'siden', 'derimot', 'likevel'],
    hint: 'Bruk bindeord (På den ene siden …, derimot …).',
    conceptId: 'discourse-markers',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b1-city-pros-cons.mp3`,
  },
  {
    id: 'b1-ask-boss',
    question: 'Hvordan ville du be sjefen din om en fridag?',
    questionEnglish: 'How would you ask your boss for a day off?',
    expectedKeywords: ['kunne', 'jeg', 'lurte', 'på', 'om', 'mulig'],
    hint: 'Bruk høflig form (Jeg lurte på om …, Kunne jeg …).',
    conceptId: 'formal-informal-register',
    errorTag: 'modal-verb',
    audioUrl: `${AUDIO_BASE}/b1-ask-boss.mp3`,
  },
  {
    id: 'b1-restart-course',
    question: 'Hva ville du gjøre annerledes hvis du kunne begynne på norskkurset på nytt?',
    questionEnglish: 'What would you do differently if you could start the Norwegian course over?',
    expectedKeywords: ['hvis', 'ville', 'kunne', 'øvd', 'mer', 'snakket'],
    hint: "Bruk 'hvis' + ville (Hvis jeg kunne …, ville jeg …).",
    conceptId: 'complex-subordination',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b1-restart-course.mp3`,
  },
  {
    id: 'b1-before-norway',
    question: 'Hva hadde du allerede lært før du flyttet til Norge?',
    questionEnglish: 'What had you already learned before you moved to Norway?',
    expectedKeywords: ['hadde', 'lært', 'kunne', 'før', 'flyttet', 'allerede'],
    hint: 'Bruk preteritum perfektum (hadde lært, hadde gjort).',
    conceptId: 'past-perfect',
    errorTag: 'verb-tense',
    audioUrl: `${AUDIO_BASE}/b1-before-norway.mp3`,
  },
]

const B2_QUESTIONS: ListenRespondQuestion[] = [
  {
    id: 'b2-counterfactual',
    question: 'Hvis du hadde kunnet velge et annet yrke, hva ville du ha valgt?',
    questionEnglish: 'If you could have chosen a different career, what would you have chosen?',
    expectedKeywords: ['hadde', 'ville', 'valgt', 'blitt', 'kanskje', 'ønsket', 'drømt'],
    hint: 'Use "hvis jeg hadde... ville jeg ha..." for counterfactual conditions.',
    conceptId: 'subjunctive-mood',
    errorTag: 'verb-tense',
    audioUrl: '',
  },
  {
    id: 'b2-argumentation',
    question: 'Selv om klimaendringer er et globalt problem, hva kan enkeltpersoner gjøre?',
    questionEnglish: 'Even though climate change is a global problem, what can individuals do?',
    expectedKeywords: ['selv', 'om', 'likevel', 'derimot', 'kan', 'gjøre', 'bidra', 'redusere'],
    hint: 'Use "selv om" (even though) and contrast markers like "likevel" or "derimot".',
    conceptId: 'complex-argumentation',
    errorTag: 'word-order',
    audioUrl: '',
  },
  {
    id: 'b2-reported-speech',
    question: 'Hva sa læreren din at du måtte jobbe med?',
    questionEnglish: 'What did your teacher say you needed to work on?',
    expectedKeywords: ['sa', 'måtte', 'burde', 'skulle', 'jobbe', 'forbedre', 'øve'],
    hint: 'Report what was said: "Læreren sa at jeg måtte..." — notice the tense backshift.',
    conceptId: 'reported-speech-advanced',
    errorTag: 'verb-tense',
    audioUrl: '',
  },
  {
    id: 'b2-topicalize',
    question: 'Den boken du nevnte — har du lest den ferdig?',
    questionEnglish: 'That book you mentioned — have you finished reading it?',
    expectedKeywords: ['den', 'boken', 'lest', 'ferdig', 'ja', 'nei', 'nesten', 'holder'],
    hint: 'Respond naturally — notice how the topic is fronted for focus in the question.',
    conceptId: 'advanced-word-order',
    errorTag: 'word-order',
    audioUrl: '',
  },
  {
    id: 'b2-academic',
    question: 'Hva kan hevdes å være den viktigste faktoren for språklæring?',
    questionEnglish: 'What could be argued to be the most important factor in language learning?',
    expectedKeywords: ['hevdes', 'hevde', 'antyde', 'ifølge', 'forskning', 'viser', 'motivasjon'],
    hint: 'Use formal hedging verbs: "det kan hevdes at...", "ifølge forskning...".',
    conceptId: 'academic-writing',
    errorTag: 'wrong-word-same-category',
    audioUrl: '',
  },
  {
    id: 'b2-advanced-passive',
    question: 'Hvorfor holdes noen opplysninger tilbake i offentlige dokumenter?',
    questionEnglish: 'Why is some information withheld in public documents?',
    expectedKeywords: ['holdes', 'tilbake', 'beskytter', 'sikkerhet', 'personvern', 'loven', 'regler'],
    hint: 'The question uses an -s passive for habitual action — respond in kind.',
    conceptId: 'advanced-passive',
    errorTag: 'verb-conjugation',
    audioUrl: '',
  },
  {
    id: 'b2-professional',
    question: 'Hvordan ville du ta ordet i et møte på norsk?',
    questionEnglish: 'How would you take the floor in a meeting in Norwegian?',
    expectedKeywords: ['ta', 'ordet', 'vil', 'gjerne', 'legge', 'til', 'spørsmål', 'mener'],
    hint: 'Use meeting phrases: "Jeg vil gjerne ta ordet", "Jeg vil legge til at...".',
    conceptId: 'professional-norwegian',
    errorTag: 'meaning-misunderstood',
    audioUrl: '',
  },
  {
    id: 'b2-idiom-advanced',
    question: 'Har du noen gang måttet bite i det sure eplet?',
    questionEnglish: 'Have you ever had to bite the bullet (do something unpleasant)?',
    expectedKeywords: ['bite', 'eplet', 'måtte', 'gjøre', 'ubehagelig', 'valg', 'situasjon'],
    hint: '"Å bite i det sure eplet" means to bite the bullet — describe such a situation.',
    conceptId: 'norwegian-idioms',
    errorTag: 'meaning-misunderstood',
    audioUrl: '',
  },
  // Batch 2 deepening (2026-06-28, linguist-reviewed; audio generated via edge-tts nb-NO-PernilleNeural).
  {
    id: 'b2-polite-disagree',
    question: 'Hvordan ville du uttrykke uenighet på en høflig måte i et møte?',
    questionEnglish: 'How would you express disagreement politely in a meeting?',
    expectedKeywords: ['jeg', 'ser', 'poenget', 'men', 'kanskje', 'likevel'],
    hint: 'Bruk dempet, høflig register (Jeg ser poenget, men …).',
    conceptId: 'nuanced-register',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b2-polite-disagree.mp3`,
  },
  {
    id: 'b2-job-process',
    question: 'Beskriv prosessen med å søke på en jobb, steg for steg.',
    questionEnglish: 'Describe the process of applying for a job, step by step.',
    expectedKeywords: ['først', 'deretter', 'så', 'til', 'slutt', 'etterpå'],
    hint: 'Bind sammen med tekstmarkører (først, deretter, til slutt).',
    conceptId: 'text-cohesion',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b2-job-process.mp3`,
  },
  {
    id: 'b2-counterfactual-offer',
    question: 'Hva ville du ha gjort dersom du hadde fått tilbudet?',
    questionEnglish: 'What would you have done if you had received the offer?',
    expectedKeywords: ['ville', 'ha', 'gjort', 'dersom', 'hadde', 'takket'],
    hint: 'Bruk sammensatt kondisjonalis (ville ha gjort).',
    conceptId: 'advanced-verb-forms',
    errorTag: 'verb-tense',
    audioUrl: `${AUDIO_BASE}/b2-counterfactual-offer.mp3`,
  },
  {
    id: 'b2-explain-simply',
    question: 'Hvordan ville du forklare et vanskelig faglig begrep til en venn?',
    questionEnglish: 'How would you explain a difficult technical concept to a friend?',
    expectedKeywords: ['enkelt', 'med', 'andre', 'ord', 'altså', 'eksempel'],
    hint: 'Tilpass stilen til mottakeren (med andre ord, altså …).',
    conceptId: 'stylistic-variation',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b2-explain-simply.mp3`,
  },
  {
    id: 'b2-regulate-privacy',
    question: 'I hvilken grad bør staten regulere folks privatliv?',
    questionEnglish: "To what extent should the state regulate people's private lives?",
    expectedKeywords: ['på', 'den', 'ene', 'siden', 'bør', 'balanse'],
    hint: 'Argumenter balansert (På den ene siden …, på den andre siden …).',
    conceptId: 'complex-argumentation',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b2-regulate-privacy.mp3`,
  },
  {
    id: 'b2-summarize-study',
    question: 'Hvordan ville du oppsummere hovedfunnene i en undersøkelse?',
    questionEnglish: 'How would you summarize the main findings of a study?',
    expectedKeywords: ['undersøkelsen', 'viser', 'at', 'resultatene', 'tyder', 'på'],
    hint: 'Bruk akademiske formler (Undersøkelsen viser at …).',
    conceptId: 'academic-writing',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b2-summarize-study.mp3`,
  },
  {
    id: 'b2-fronting-surprise',
    question: 'Mange synes norsk er overraskende — hva overrasket deg mest med norsk?',
    questionEnglish: 'Many find Norwegian surprising — what surprised you most about Norwegian?',
    expectedKeywords: ['mest', 'overrasket', 'var', 'grammatikken', 'ordstillingen', 'uttalen'],
    hint: 'Bruk inversjon ved fronting (Mest overrasket grammatikken meg …).',
    conceptId: 'advanced-word-order',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b2-fronting-surprise.mp3`,
  },
  {
    id: 'b2-present-proposal',
    question: 'Hvordan ville du presentere et forslag for ledelsen?',
    questionEnglish: 'How would you present a proposal to management?',
    expectedKeywords: ['jeg', 'vil', 'foreslå', 'anbefaler', 'fordelene', 'gjennomføre'],
    hint: 'Bruk profesjonelt språk (Jeg vil foreslå at …).',
    conceptId: 'professional-norwegian',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/b2-present-proposal.mp3`,
  },
]

// A2 = combination level: perfect tense, modals, comparatives, conditionals,
// subordinate clauses, time expressions, reflexives, object pronouns. Each prompt
// elicits production of one A2 structure. Linguist-reviewed 2026-06-27 (18 PASS;
// a2-if-dayoff + a2-relax hint corrected; audio generated via edge-tts
// nb-NO-PernilleNeural).
const A2_QUESTIONS: ListenRespondQuestion[] = [
  {
    id: 'a2-perfect-week',
    question: 'Hva har du gjort denne uka?',
    questionEnglish: 'What have you done this week?',
    expectedKeywords: ['har', 'jobbet', 'vært', 'spist', 'møtt', 'gjort', 'trent'],
    hint: 'Bruk perfektum: har + partisipp (har jobbet, har vært).',
    conceptId: 'perfect-tense',
    errorTag: 'verb-tense',
    audioUrl: `${AUDIO_BASE}/a2-perfect-week.mp3`,
  },
  {
    id: 'a2-compare-cities',
    question: 'Er det dyrere å bo i Oslo enn i Bergen?',
    questionEnglish: 'Is it more expensive to live in Oslo than in Bergen?',
    expectedKeywords: ['dyrere', 'billigere', 'enn', 'mer', 'mindre', 'tror'],
    hint: 'Sammenlign med adjektiv + -ere … enn (dyrere enn).',
    conceptId: 'comparative-adjectives',
    errorTag: 'adjective-agreement',
    audioUrl: `${AUDIO_BASE}/a2-compare-cities.mp3`,
  },
  {
    id: 'a2-must-before-weekend',
    question: 'Hva må du gjøre før helga?',
    questionEnglish: 'What do you have to do before the weekend?',
    expectedKeywords: ['må', 'skal', 'bør', 'kan', 'jobbe', 'handle', 'gjøre'],
    hint: 'Bruk modalverb (må, skal, bør) + infinitiv.',
    conceptId: 'modal-verbs-advanced',
    errorTag: 'modal-verb',
    audioUrl: `${AUDIO_BASE}/a2-must-before-weekend.mp3`,
  },
  {
    id: 'a2-when-home',
    question: 'Hva gjør du når du kommer hjem fra jobb?',
    questionEnglish: 'What do you do when you come home from work?',
    expectedKeywords: ['når', 'kommer', 'hjem', 'lager', 'slapper', 'hviler'],
    hint: "Bruk en leddsetning med 'når' (… når jeg kommer hjem).",
    conceptId: 'subordinate-clauses',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/a2-when-home.mp3`,
  },
  {
    id: 'a2-if-dayoff',
    question: 'Hva ville du gjøre hvis du hadde fri i morgen?',
    questionEnglish: 'What would you do if you had a day off tomorrow?',
    expectedKeywords: ['hvis', 'ville', 'hadde', 'sove', 'reise', 'slappe'],
    hint: "Bruk 'hvis' + ville (Hvis jeg hadde fri, ville jeg …).",
    conceptId: 'conditional-clauses',
    errorTag: 'word-order',
    audioUrl: `${AUDIO_BASE}/a2-if-dayoff.mp3`,
  },
  {
    id: 'a2-dinner-time',
    question: 'Når pleier du å spise middag?',
    questionEnglish: 'When do you usually eat dinner?',
    expectedKeywords: ['klokka', 'fem', 'seks', 'sju', 'om', 'kvelden', 'pleier'],
    hint: 'Bruk tidsuttrykk (klokka seks, om kvelden).',
    conceptId: 'time-expressions',
    errorTag: 'preposition',
    audioUrl: `${AUDIO_BASE}/a2-dinner-time.mp3`,
  },
  {
    id: 'a2-relax',
    question: 'Hva gjør du for å slappe av etter en lang dag?',
    questionEnglish: 'What do you do to relax after a long day?',
    expectedKeywords: ['slapper', 'av', 'koser', 'meg', 'hviler', 'ser'],
    hint: 'Bruk refleksivt verb eller partikkelverb (kose seg, slappe av).',
    conceptId: 'reflexive-verbs',
    errorTag: 'pronoun-choice',
    audioUrl: `${AUDIO_BASE}/a2-relax.mp3`,
  },
  {
    id: 'a2-who-help',
    question: 'Hvem hjelper du ofte, og hvordan?',
    questionEnglish: 'Who do you often help, and how?',
    expectedKeywords: ['hjelper', 'henne', 'ham', 'dem', 'familien', 'med'],
    hint: 'Bruk objektspronomen (ham, henne, dem).',
    conceptId: 'object-pronouns',
    errorTag: 'pronoun-choice',
    audioUrl: `${AUDIO_BASE}/a2-who-help.mp3`,
  },
]

/** @deprecated use getListenQuestions(level) instead */
export const LISTEN_RESPOND_QUESTIONS: ListenRespondQuestion[] = A1_QUESTIONS

/**
 * Returns the listen-respond question set appropriate for the learner's CEFR level.
 * Falls back to A1 questions for A2 and unknown levels.
 */
export function getListenQuestions(level: string): ListenRespondQuestion[] {
  if (level === 'B2') return B2_QUESTIONS
  if (level === 'B1') return B1_QUESTIONS
  if (level === 'A2') return A2_QUESTIONS
  return A1_QUESTIONS
}

/**
 * The CEFR level whose listen-respond questions are ACTUALLY served for a
 * learner level. A1/A2/B1/B2 all have dedicated sets now; only unknown levels
 * fall back to A1. Exposing this lets the UI honestly disclose below-level
 * content instead of substituting silently (Operating Rule 6), mirroring
 * getRoleplayContentLevel.
 */
export function getListenContentLevel(level: string): string {
  if (level === 'B2') return 'B2'
  if (level === 'B1') return 'B1'
  if (level === 'A2') return 'A2'
  if (level === 'A1') return 'A1'
  return 'A1' // unknown → A1 questions
}
