import type { ErrorTag } from '@/types/taxonomy'

export interface RoleplayTurn {
  id: string
  character: string          // Norwegian line
  characterEnglish: string   // English subtitle
  expectedKeywords: string[] // normalised lowercase — any one match = pass
  hint: string               // coaching tip on fallback
  modelAnswer: string        // "Prøv å si: ..." shown on retry
  targetConceptId: string    // Concept this turn exposes — MUST exist in the level's graph
  errorTag: ErrorTag         // Tag used when the user's answer misses
}

export interface RoleplayScenario {
  id: string
  title: string
  titleEnglish: string
  setting: string            // English context shown before start
  characterName: string
  turns: RoleplayTurn[]
}

const A1_SCENARIOS: RoleplayScenario[] = [
  {
    id: 'kaffe',
    title: 'Bestille kaffe',
    titleEnglish: 'Ordering coffee',
    setting: "You're at a café in Oslo. The barista greets you.",
    characterName: 'Barista',
    turns: [
      {
        id: 'greet',
        character: 'Hei! Hva kan jeg hjelpe deg med?',
        characterEnglish: 'Hi! What can I help you with?',
        expectedKeywords: ['kaffe', 'latte', 'cappuccino', 'espresso', 'vil', 'ha', 'gjerne'],
        hint: 'Order something to drink.',
        modelAnswer: 'Jeg vil gjerne ha en kaffe, takk.',
        targetConceptId: 'common-modal-verbs',
        errorTag: 'modal-verb',
      },
      {
        id: 'size',
        character: 'Stor eller liten?',
        characterEnglish: 'Large or small?',
        expectedKeywords: ['stor', 'liten', 'medium'],
        hint: 'Choose a size.',
        modelAnswer: 'Stor, takk.',
        targetConceptId: 'basic-adjectives',
        errorTag: 'adjective-agreement',
      },
      {
        id: 'name',
        character: 'Hva er navnet ditt?',
        characterEnglish: 'What is your name?',
        expectedKeywords: ['heter', 'navn', 'jeg', 'er'],
        hint: 'Tell them your name.',
        modelAnswer: 'Jeg heter [ditt navn].',
        targetConceptId: 'personal-pronouns',
        errorTag: 'pronoun-choice',
      },
      {
        id: 'thanks',
        character: 'Det blir femti kroner. Ha en fin dag!',
        characterEnglish: "That's fifty kroner. Have a nice day!",
        expectedKeywords: ['takk', 'tusen', 'deg', 'også', 'ha'],
        hint: 'Say thank you.',
        modelAnswer: 'Takk! Ha det bra.',
        targetConceptId: 'to-have-verb',
        errorTag: 'verb-conjugation',
      },
    ],
  },
  {
    id: 'veibeskrivelse',
    title: 'Be om veibeskrivelse',
    titleEnglish: 'Asking for directions',
    setting: "You're lost in the city. A passerby offers to help.",
    characterName: 'Forbipasserende',
    turns: [
      {
        id: 'excuse',
        character: 'Hei, kan jeg hjelpe deg?',
        characterEnglish: 'Hi, can I help you?',
        expectedKeywords: ['unnskyld', 'hjelp', 'stasjon', 'togstasjon', 'buss', 'veien', 'hvor'],
        hint: 'Ask for directions somewhere.',
        modelAnswer: 'Unnskyld, hvor er togstasjonen?',
        targetConceptId: 'question-formation',
        errorTag: 'word-order',
      },
      {
        id: 'understand',
        character: 'Togstasjonen er rett frem og til venstre ved lyskrysset.',
        characterEnglish: 'The train station is straight ahead and left at the traffic light.',
        expectedKeywords: ['forstår', 'ok', 'takk', 'skjønner', 'frem', 'venstre'],
        hint: 'Confirm you understand.',
        modelAnswer: 'Ok, rett frem og til venstre. Takk!',
        targetConceptId: 'common-prepositions',
        errorTag: 'preposition',
      },
      {
        id: 'howfar',
        character: 'Det tar omtrent fem minutter å gå.',
        characterEnglish: "It's about a five-minute walk.",
        expectedKeywords: ['takk', 'minutter', 'greit', 'bra', 'perfekt'],
        hint: 'Respond to the time estimate.',
        modelAnswer: 'Fem minutter — perfekt, takk så mye.',
        targetConceptId: 'numbers-basic',
        errorTag: 'spelling',
      },
      {
        id: 'bye',
        character: 'Bare hyggelig! God tur!',
        characterEnglish: "You're welcome! Safe travels!",
        expectedKeywords: ['takk', 'ha', 'det', 'bra', 'hyggelig'],
        hint: 'Say goodbye.',
        modelAnswer: 'Takk! Ha det bra!',
        targetConceptId: 'to-have-verb',
        errorTag: 'verb-conjugation',
      },
    ],
  },
  {
    id: 'introduksjon',
    title: 'Introdusere deg selv',
    titleEnglish: 'Introducing yourself',
    setting: 'First day at a new job. A colleague introduces themselves.',
    characterName: 'Kollega',
    turns: [
      {
        id: 'meet',
        character: 'Hei! Jeg heter Kari. Er du ny her?',
        characterEnglish: "Hi! I'm Kari. Are you new here?",
        expectedKeywords: ['heter', 'hei', 'ja', 'ny', 'navn', 'jeg'],
        hint: 'Introduce yourself.',
        modelAnswer: 'Hei! Jeg heter [ditt navn]. Ja, jeg er ny.',
        targetConceptId: 'personal-pronouns',
        errorTag: 'pronoun-choice',
      },
      {
        id: 'from',
        character: 'Hyggelig å møte deg! Hvor er du fra?',
        characterEnglish: 'Nice to meet you! Where are you from?',
        expectedKeywords: ['fra', 'bor', 'land', 'england', 'usa', 'norge', 'australia'],
        hint: 'Say where you are from.',
        modelAnswer: 'Jeg er fra England.',
        targetConceptId: 'common-prepositions',
        errorTag: 'preposition',
      },
      {
        id: 'work',
        character: 'Spennende! Hva jobber du med her?',
        characterEnglish: 'Interesting! What will you be doing here?',
        expectedKeywords: ['jobber', 'arbeider', 'avdeling', 'prosjekt', 'design', 'kode', 'salg'],
        hint: 'Describe your role.',
        modelAnswer: 'Jeg jobber med design.',
        targetConceptId: 'common-prepositions',
        errorTag: 'preposition',
      },
      {
        id: 'coffee',
        character: 'Kjempebra! Vil du ha en kopp kaffe?',
        characterEnglish: 'Great! Would you like a cup of coffee?',
        expectedKeywords: ['ja', 'takk', 'gjerne', 'kaffe', 'vil', 'ha'],
        hint: 'Accept or politely decline.',
        modelAnswer: 'Ja, gjerne! Tusen takk.',
        targetConceptId: 'common-modal-verbs',
        errorTag: 'modal-verb',
      },
    ],
  },
  // Batch 3 deepening (2026-06-28, linguist-reviewed).
  {
    id: 'a1-restaurant',
    title: 'Bestille mat på kafé',
    titleEnglish: 'Ordering food at a café',
    setting: "You're at a café and want to order something to eat and drink.",
    characterName: 'Servitør',
    turns: [
      {
        id: 'order',
        character: 'Hei! Hva vil du ha?',
        characterEnglish: 'Hi! What would you like?',
        expectedKeywords: ['vil', 'ha', 'kaffe', 'bolle', 'takk', 'en'],
        hint: 'Bruk modalverb (Jeg vil ha …).',
        modelAnswer: 'Jeg vil ha en kaffe og en bolle, takk.',
        targetConceptId: 'common-modal-verbs',
        errorTag: 'modal-verb',
      },
      {
        id: 'size',
        character: 'Vil du ha en stor eller liten kaffe?',
        characterEnglish: 'Would you like a large or small coffee?',
        expectedKeywords: ['stor', 'liten', 'takk', 'en'],
        hint: 'Velg med et adjektiv (en stor kaffe).',
        modelAnswer: 'En stor, takk.',
        targetConceptId: 'basic-adjectives',
        errorTag: 'adjective-agreement',
      },
      {
        id: 'drink',
        character: 'Vil du ha noe å drikke også?',
        characterEnglish: 'Would you like something to drink as well?',
        expectedKeywords: ['et', 'glass', 'vann', 'ja', 'juice'],
        hint: 'Bruk riktig artikkel (et glass vann).',
        modelAnswer: 'Ja, et glass vann, takk.',
        targetConceptId: 'indefinite-articles',
        errorTag: 'article-use',
      },
      {
        id: 'pay',
        character: 'Hvordan vil du betale?',
        characterEnglish: 'How would you like to pay?',
        expectedKeywords: ['med', 'kort', 'kontant', 'takk'],
        hint: 'Bruk preposisjon (betale med kort).',
        modelAnswer: 'Med kort, takk.',
        targetConceptId: 'common-prepositions',
        errorTag: 'preposition',
      },
    ],
  },
  {
    id: 'a1-apotek',
    title: 'På apoteket',
    titleEnglish: 'At the pharmacy',
    setting: "You're at the pharmacy and need something for a headache.",
    characterName: 'Apoteker',
    turns: [
      {
        id: 'need',
        character: 'Hei, hva kan jeg hjelpe deg med?',
        characterEnglish: 'Hi, what can I help you with?',
        expectedKeywords: ['trenger', 'noe', 'mot', 'hodepine', 'vondt'],
        hint: 'Si hva du trenger (Jeg trenger noe mot …).',
        modelAnswer: 'Jeg trenger noe mot hodepine.',
        targetConceptId: 'present-tense-regular',
        errorTag: 'verb-conjugation',
      },
      {
        id: 'form',
        character: 'Vil du ha en flaske mikstur eller et brett med tabletter?',
        characterEnglish: 'Would you like a bottle of liquid medicine or a pack of tablets?',
        expectedKeywords: ['et', 'brett', 'tabletter', 'en', 'flaske'],
        hint: 'Velg med riktig artikkel (en flaske / et brett).',
        modelAnswer: 'Et brett med tabletter, takk.',
        targetConceptId: 'noun-gender',
        errorTag: 'noun-gender',
      },
      {
        id: 'amount',
        character: 'Hvor mange trenger du?',
        characterEnglish: 'How many do you need?',
        expectedKeywords: ['en', 'pakke', 'to', 'holder', 'nok'],
        hint: 'Bruk riktig artikkel og mengde (En pakke holder).',
        modelAnswer: 'En pakke holder.',
        targetConceptId: 'indefinite-articles',
        errorTag: 'article-use',
      },
      {
        id: 'pay',
        character: 'Det blir 79 kroner. Betaler du med kort?',
        characterEnglish: "That'll be 79 kroner. Are you paying by card?",
        expectedKeywords: ['ja', 'med', 'kort', 'kontant'],
        hint: 'Bruk preposisjon (med kort).',
        modelAnswer: 'Ja, med kort.',
        targetConceptId: 'common-prepositions',
        errorTag: 'preposition',
      },
    ],
  },
]

const B1_SCENARIOS: RoleplayScenario[] = [
  {
    id: 'lege',
    title: 'Hos legen',
    titleEnglish: 'At the doctor',
    setting: "You have an appointment with your GP in Norway. The doctor greets you.",
    characterName: 'Lege',
    turns: [
      {
        id: 'lege-greet',
        character: 'Hei, kom inn! Hva kan jeg hjelpe deg med i dag?',
        characterEnglish: 'Hi, come in! What can I help you with today?',
        expectedKeywords: ['har', 'vondt', 'feber', 'hode', 'mage', 'syk', 'vondt', 'siden'],
        hint: 'Describe your symptoms: "Jeg har hatt vondt i..."',
        modelAnswer: 'Jeg har hatt vondt i halsen siden i går.',
        targetConceptId: 'past-perfect',
        errorTag: 'verb-tense',
      },
      {
        id: 'lege-how-long',
        character: 'Hvor lenge har du hatt disse plagene?',
        characterEnglish: 'How long have you had these symptoms?',
        expectedKeywords: ['dager', 'uker', 'siden', 'begynte', 'hadde', 'mandag', 'onsdag'],
        hint: 'Say how long: "Jeg har hatt det siden..." or "i ... dager".',
        modelAnswer: 'Jeg har hatt det i tre dager — det begynte mandag.',
        targetConceptId: 'past-perfect',
        errorTag: 'verb-tense',
      },
      {
        id: 'lege-medicine',
        character: 'Har du tatt noen medisiner?',
        characterEnglish: 'Have you taken any medicine?',
        expectedKeywords: ['tatt', 'paracet', 'ibux', 'medisin', 'nei', 'ja', 'prøvd'],
        hint: 'Say whether you have taken anything: "Jeg har tatt..." or "Jeg har ikke tatt...".',
        modelAnswer: 'Jeg har tatt paracetamol, men det hjalp ikke så mye.',
        targetConceptId: 'idiomatic-expressions',
        errorTag: 'meaning-misunderstood',
      },
      {
        id: 'lege-advice',
        character: 'Jeg anbefaler deg å hvile og drikke mye vann. Er det noe annet?',
        characterEnglish: 'I recommend you rest and drink plenty of water. Is there anything else?',
        expectedKeywords: ['takk', 'lurer', 'om', 'spørsmål', 'forstår', 'greit', 'bra'],
        hint: 'Thank the doctor or ask a follow-up question.',
        modelAnswer: 'Takk. Jeg lurer på om jeg trenger sykmelding.',
        targetConceptId: 'indirect-questions',
        errorTag: 'word-order',
      },
    ],
  },
  {
    id: 'jobbintervju',
    title: 'Jobbintervju',
    titleEnglish: 'Job interview',
    setting: "You are being interviewed for a position at a Norwegian company. The interviewer welcomes you.",
    characterName: 'Intervjuer',
    turns: [
      {
        id: 'intervju-intro',
        character: 'Velkommen! Kan du fortelle litt om deg selv og bakgrunnen din?',
        characterEnglish: 'Welcome! Can you tell us a bit about yourself and your background?',
        expectedKeywords: ['heter', 'jobbet', 'studert', 'erfaring', 'bakgrunn', 'tidligere', 'har'],
        hint: 'Introduce yourself and mention your experience: "Jeg har jobbet med..." or "Jeg har studert...".',
        modelAnswer: 'Jeg heter [navn] og har jobbet med markedsføring i tre år.',
        targetConceptId: 'past-perfect',
        errorTag: 'verb-tense',
      },
      {
        id: 'intervju-strengths',
        character: 'Hva vil du si er dine sterkeste sider?',
        characterEnglish: 'What would you say are your strongest qualities?',
        expectedKeywords: ['er', 'flink', 'god', 'sterk', 'side', 'løsningsorientert', 'strukturert', 'samarbeider'],
        hint: 'Name a strength: "Jeg er flink til å..." or "En av mine sterkeste sider er...".',
        modelAnswer: 'Jeg er løsningsorientert og god til å samarbeide med andre.',
        targetConceptId: 'formal-informal-register',
        errorTag: 'wrong-word-same-category',
      },
      {
        id: 'intervju-why',
        character: 'Hvorfor søker du akkurat denne stillingen?',
        characterEnglish: 'Why are you applying for this particular position?',
        expectedKeywords: ['fordi', 'interessert', 'liker', 'ønsker', 'bidra', 'utvikle', 'mulighet'],
        hint: 'Give a reason: "Jeg søker fordi jeg er interessert i..." or "Jeg ønsker å bidra med...".',
        modelAnswer: 'Jeg søker fordi jeg er interessert i å utvikle meg innen denne bransjen.',
        targetConceptId: 'discourse-markers',
        errorTag: 'meaning-misunderstood',
      },
      {
        id: 'intervju-close',
        character: 'Takk for det! Har du noen spørsmål til oss?',
        characterEnglish: 'Thank you for that! Do you have any questions for us?',
        expectedKeywords: ['lurer', 'om', 'spørsmål', 'vet', 'hva', 'når', 'oppstartsdato', 'teamet'],
        hint: 'Ask a question: "Jeg lurer på om..." or "Kan dere fortelle meg litt om...".',
        modelAnswer: 'Ja, jeg lurer på om dere kan fortelle litt om teamet jeg ville jobbe i.',
        targetConceptId: 'indirect-questions',
        errorTag: 'word-order',
      },
    ],
  },
  {
    id: 'restaurant-klage',
    title: 'Klage på restauranten',
    titleEnglish: 'Complaining at a restaurant',
    setting: "You ordered a meal at a Norwegian restaurant but there is a problem with your order. The waiter comes over.",
    characterName: 'Kelner',
    turns: [
      {
        id: 'klage-problem',
        character: 'Hei, er alt i orden?',
        characterEnglish: 'Hi, is everything all right?',
        expectedKeywords: ['nei', 'dessverre', 'bestilte', 'feil', 'kald', 'rå', 'problem', 'riktig'],
        hint: 'Point out the problem: "Jeg bestilte... men fikk..." or "Maten er...".',
        modelAnswer: 'Nei, dessverre. Jeg bestilte laksen, men maten er kald.',
        targetConceptId: 'phrasal-verbs',
        errorTag: 'preposition',
      },
      {
        id: 'klage-sorry',
        character: 'Beklager det. Vil du at vi varmer den opp, eller vil du ha noe annet?',
        characterEnglish: 'I apologise for that. Would you like us to heat it up, or would you prefer something else?',
        expectedKeywords: ['vil', 'gjerne', 'varme', 'opp', 'heller', 'annet', 'bytte', 'takk'],
        hint: 'Choose: ask them to heat it up or swap the dish.',
        modelAnswer: 'Jeg vil gjerne at dere varmer den opp, takk.',
        targetConceptId: 'phrasal-verbs',
        errorTag: 'preposition',
      },
      {
        id: 'klage-discount',
        character: 'Selvfølgelig. Og vi gir deg ti prosent rabatt på regningen.',
        characterEnglish: 'Of course. And we will give you a ten percent discount on the bill.',
        expectedKeywords: ['takk', 'tusen', 'setter', 'pris', 'hyggelig', 'snill', 'flott'],
        hint: 'Accept the gesture graciously: "Tusen takk, det setter jeg pris på."',
        modelAnswer: 'Tusen takk, det setter jeg veldig pris på.',
        targetConceptId: 'idiomatic-expressions',
        errorTag: 'meaning-misunderstood',
      },
      {
        id: 'klage-bill',
        character: 'Her er den nye regningen. Betaler du med kort?',
        characterEnglish: 'Here is the new bill. Are you paying by card?',
        expectedKeywords: ['ja', 'kort', 'vipps', 'kontant', 'betaler', 'her'],
        hint: 'Confirm payment method.',
        modelAnswer: 'Ja, jeg betaler med kort. Takk for hjelpen.',
        targetConceptId: 'formal-informal-register',
        errorTag: 'wrong-word-same-category',
      },
    ],
  },
  // Batch 3 deepening (2026-06-28, linguist-reviewed).
  {
    id: 'b1-leilighet',
    title: 'Se på en leilighet',
    titleEnglish: 'Viewing an apartment',
    setting: "You're viewing an apartment to rent. The estate agent shows you around.",
    characterName: 'Eiendomsmegler',
    turns: [
      {
        id: 'priority',
        character: 'Velkommen! Hva er det viktigste for deg i en leilighet?',
        characterEnglish: "Welcome! What's the most important thing for you in an apartment?",
        expectedKeywords: ['det', 'er', 'god', 'plass', 'som', 'viktigste'],
        hint: 'Bruk kløyvd setning: Det er [X] som er [Y].',
        modelAnswer: 'Det er god plass som er det viktigste for meg.',
        targetConceptId: 'cleft-sentences',
        errorTag: 'word-order',
      },
      {
        id: 'experience',
        character: 'Bodde du andre steder i Norge før du flyttet hit?',
        characterEnglish: 'Did you live other places in Norway before you moved here?',
        expectedKeywords: ['hadde', 'leid', 'bodde', 'før', 'flyttet', 'bergen'],
        hint: 'Bruk preteritum perfektum (Jeg hadde leid … før jeg flyttet).',
        modelAnswer: 'Ja, jeg hadde leid en leilighet i Bergen før jeg flyttet hit.',
        targetConceptId: 'past-perfect',
        errorTag: 'verb-tense',
      },
      {
        id: 'condition',
        character: 'Hva ville være avgjørende for at du skal si ja?',
        characterEnglish: 'What would be decisive for you to say yes?',
        expectedKeywords: ['hvis', 'fordi', 'nær', 'pris', 'rimelig'],
        hint: 'Bruk leddsetning (… hvis prisen er rimelig og det er nær jobben).',
        modelAnswer: 'Jeg sier ja hvis prisen er rimelig og det er nær jobben.',
        targetConceptId: 'complex-subordination',
        errorTag: 'word-order',
      },
      {
        id: 'booking',
        character: 'Skal jeg sette deg opp som interessent?',
        characterEnglish: 'Shall I register you as an interested party?',
        expectedKeywords: ['ja', 'gjerne', 'kunne', 'sende', 'detaljene', 'takk'],
        hint: 'Bruk høflig form (Kunne du sende meg detaljene?).',
        modelAnswer: 'Ja gjerne, kunne du sende meg detaljene?',
        targetConceptId: 'formal-informal-register',
        errorTag: 'modal-verb',
      },
    ],
  },
  {
    id: 'b1-reklamasjon',
    title: 'Reklamere på en vare',
    titleEnglish: 'Returning a faulty product',
    setting: "You're returning a jacket that broke. You talk to customer service.",
    characterName: 'Kundeservice',
    turns: [
      {
        id: 'issue',
        character: 'Hei, hva kan jeg hjelpe deg med?',
        characterEnglish: 'Hi, what can I help you with?',
        expectedKeywords: ['levere', 'tilbake', 'gikk', 'stykker', 'bytte'],
        hint: 'Bruk partikkelverb (levere tilbake, gå i stykker).',
        modelAnswer: 'Jeg vil levere tilbake denne jakka, den gikk i stykker.',
        targetConceptId: 'phrasal-verbs',
        errorTag: 'preposition',
      },
      {
        id: 'when',
        character: 'Når kjøpte du den?',
        characterEnglish: 'When did you buy it?',
        expectedKeywords: ['kjøpte', 'uke', 'siden', 'hadde', 'ryket'],
        hint: 'Bruk fortid og preteritum perfektum (… hadde allerede ryket).',
        modelAnswer: 'Jeg kjøpte den for en uke siden, og glidelåsen hadde allerede ryket.',
        targetConceptId: 'past-perfect',
        errorTag: 'verb-tense',
      },
      {
        id: 'preference',
        character: 'Vil du ha pengene tilbake eller bytte?',
        characterEnglish: 'Do you want a refund or an exchange?',
        expectedKeywords: ['helst', 'men', 'hvis', 'eller', 'heller'],
        hint: 'Bruk bindeord (Helst …, men hvis …).',
        modelAnswer: 'Helst pengene tilbake, men hvis det ikke går, kan jeg bytte.',
        targetConceptId: 'discourse-markers',
        errorTag: 'word-order',
      },
      {
        id: 'receipt',
        character: 'Har du kvitteringen?',
        characterEnglish: 'Do you have the receipt?',
        expectedKeywords: ['ja', 'kvittering', 'kunne', 'her', 'takk'],
        hint: 'Bruk høflig form (Kunne du hjelpe meg videre?).',
        modelAnswer: 'Ja, her er den. Kunne du hjelpe meg videre?',
        targetConceptId: 'formal-informal-register',
        errorTag: 'modal-verb',
      },
    ],
  },
]

const B2_SCENARIOS: RoleplayScenario[] = [
  {
    id: 'debatt',
    title: 'Debattere et tema',
    titleEnglish: 'Debating a topic',
    setting: "You are in a panel discussion about whether Norwegian universities should offer more English-language programmes. Your debate partner opens.",
    characterName: 'Debattpartner',
    turns: [
      {
        id: 'debatt-thesis',
        character: 'Jeg mener at universiteter bør tilby flere engelskspråklige programmer for å tiltrekke internasjonale studenter. Hva mener du?',
        characterEnglish: 'I think universities should offer more English-language programmes to attract international students. What do you think?',
        expectedKeywords: ['mener', 'selv', 'om', 'likevel', 'derimot', 'enig', 'uenig', 'imidlertid'],
        hint: 'State your position with a concessive or contrastive marker: "Selv om... mener jeg at..." or "Jeg er delvis enig, men derimot...".',
        modelAnswer: 'Jeg er delvis enig, men jeg mener likevel at norsk bør forbli det primære undervisningsspråket.',
        targetConceptId: 'complex-argumentation',
        errorTag: 'word-order',
      },
      {
        id: 'debatt-counter',
        character: 'Men forskning viser jo at internasjonalisering styrker kvaliteten på utdanningen.',
        characterEnglish: 'But research shows that internationalisation strengthens the quality of education.',
        expectedKeywords: ['ifølge', 'hevdes', 'antyder', 'forskning', 'derimot', 'det', 'kan', 'argumenteres'],
        hint: 'Use academic hedging: "Det kan hevdes at..." or "Ifølge annen forskning...".',
        modelAnswer: 'Det kan hevdes at internasjonalisering er viktig, men det betyr ikke nødvendigvis at vi må bytte språk.',
        targetConceptId: 'academic-writing',
        errorTag: 'wrong-word-same-category',
      },
      {
        id: 'debatt-nuance',
        character: 'Hva med de studentene som ikke snakker norsk godt nok?',
        characterEnglish: 'What about the students who do not speak Norwegian well enough?',
        expectedKeywords: ['når', 'gjelder', 'de', 'studentene', 'følgelig', 'dermed', 'støtte', 'tilbud'],
        hint: 'Use anaphoric reference: "Når det gjelder disse studentene..." or "For sistnevnte gruppe...".',
        modelAnswer: 'Når det gjelder disse studentene, bør universitetet tilby norskopplæring, ikke fjerne norsk fra fagene.',
        targetConceptId: 'text-cohesion',
        errorTag: 'reading-parsing',
      },
      {
        id: 'debatt-close',
        character: 'Interessant. Kan du oppsummere ditt syn kort?',
        characterEnglish: 'Interesting. Can you summarise your view briefly?',
        expectedKeywords: ['kort', 'sagt', 'oppsummert', 'mener', 'viktig', 'norsk', 'bevare', 'internasjonalt'],
        hint: 'Summarise with a connector: "Kort sagt mener jeg at..." or "Oppsummert er jeg av den oppfatning at...".',
        modelAnswer: 'Kort sagt mener jeg at norsk bør bevares som undervisningsspråk, selv om internasjonal profil er verdifullt.',
        targetConceptId: 'stylistic-variation',
        errorTag: 'word-order',
      },
    ],
  },
  {
    id: 'husleie',
    title: 'Forhandle om husleie',
    titleEnglish: 'Negotiating rent',
    setting: "You are meeting your landlord to discuss renewing your lease. The rent has gone up significantly and you want to negotiate.",
    characterName: 'Utleier',
    turns: [
      {
        id: 'husleie-open',
        character: 'Jeg har tenkt å øke leien med to tusen kroner fra neste måned.',
        characterEnglish: 'I am planning to increase the rent by two thousand kroner from next month.',
        expectedKeywords: ['forstår', 'imidlertid', 'likevel', 'ønsker', 'diskutere', 'lurer', 'om', 'mulig'],
        hint: 'Acknowledge and push back politely: "Jeg forstår det, men jeg lurer på om det er mulig å...".',
        modelAnswer: 'Jeg forstår det, men jeg lurer på om det er mulig å diskutere dette nærmere.',
        targetConceptId: 'nuanced-register',
        errorTag: 'pronoun-choice',
      },
      {
        id: 'husleie-justify',
        character: 'Prisene i området har steget mye. Det er markedspris.',
        characterEnglish: 'Prices in the area have risen a lot. This is market rate.',
        expectedKeywords: ['selv', 'om', 'til', 'tross', 'for', 'har', 'bodd', 'vedlikeholdt', 'aldri'],
        hint: 'Use a concessive construction: "Selv om prisene har steget, har jeg vedlikeholdt leiligheten godt...".',
        modelAnswer: 'Selv om jeg forstår at prisene har steget, har jeg bodd her i tre år uten problemer og alltid betalt i tide.',
        targetConceptId: 'complex-argumentation',
        errorTag: 'word-order',
      },
      {
        id: 'husleie-propose',
        character: 'Hva foreslår du da?',
        characterEnglish: 'What do you propose then?',
        expectedKeywords: ['foreslår', 'tilbyr', 'kompromiss', 'tusen', 'økning', 'gradvis', 'halvparten'],
        hint: 'Make a counter-offer: "Jeg foreslår at vi..." or "Hva om vi møtes på halvparten?".',
        modelAnswer: 'Jeg foreslår at vi møtes på halvparten — én tusen kroner økning i stedet for to.',
        targetConceptId: 'professional-norwegian',
        errorTag: 'meaning-misunderstood',
      },
      {
        id: 'husleie-agree',
        character: 'Det kan vi kanskje se nærmere på. Jeg viser til kontrakten vår.',
        characterEnglish: 'We could perhaps look into that. I refer to our contract.',
        expectedKeywords: ['viser', 'henvendelse', 'takk', 'sette', 'pris', 'avtale', 'skriftlig', 'enige'],
        hint: 'Close professionally: "Tusen takk. Jeg setter pris på at vi kan finne en løsning."',
        modelAnswer: 'Tusen takk. Jeg setter pris på at vi kan finne en løsning, og jeg vil gjerne ha det skriftlig.',
        targetConceptId: 'professional-norwegian',
        errorTag: 'meaning-misunderstood',
      },
    ],
  },
  {
    id: 'kulturforskjell',
    title: 'Forklare en kulturforskjell',
    titleEnglish: 'Explaining a cultural difference',
    setting: "You are at a Norwegian dinner party. A Norwegian host asks about cultural differences between Norway and your home country.",
    characterName: 'Vert',
    turns: [
      {
        id: 'kultur-open',
        character: 'Jeg er nysgjerrig — hva synes du er den største kulturelle forskjellen mellom Norge og landet ditt?',
        characterEnglish: 'I am curious — what do you think is the biggest cultural difference between Norway and your country?',
        expectedKeywords: ['mener', 'synes', 'tror', 'forskjell', 'interessant', 'særlig', 'spesielt'],
        hint: 'Give a considered opinion and set up a contrast.',
        modelAnswer: 'Jeg synes den mest interessante forskjellen er den direkte kommunikasjonsstilen i Norge.',
        targetConceptId: 'nuanced-register',
        errorTag: 'pronoun-choice',
      },
      {
        id: 'kultur-explain',
        character: 'Kan du utdype det litt?',
        characterEnglish: 'Can you elaborate on that a bit?',
        expectedKeywords: ['hadde', 'visst', 'ville', 'ha', 'om', 'bare', 'for', 'eksempel', 'dermed'],
        hint: 'Use a counterfactual or hypothetical: "Hvis jeg hadde visst dette, ville jeg ha..." or give a concrete example.',
        modelAnswer: 'For eksempel: hvis jeg hadde visst at nordmenn foretrekker direkte tilbakemeldinger, ville jeg ha tilpasset meg raskere.',
        targetConceptId: 'subjunctive-mood',
        errorTag: 'verb-tense',
      },
      {
        id: 'kultur-compare',
        character: 'Interessant! Er det noe norsk du har tatt med deg hjem?',
        characterEnglish: 'Interesting! Is there something Norwegian you have taken home with you?',
        expectedKeywords: ['tatt', 'med', 'lært', 'adoptert', 'prøver', 'friluftsliv', 'åpenhet', 'direkte'],
        hint: 'Use a phrasal construction: "Jeg har tatt med meg..." or "Jeg prøver å...".',
        modelAnswer: 'Ja, jeg har tatt med meg friluftsliv-tankegangen — å tilbringe tid ute uansett vær.',
        targetConceptId: 'advanced-word-order',
        errorTag: 'word-order',
      },
      {
        id: 'kultur-reflect',
        character: 'Det er fint å høre. Hva vil du si til noen som skal flytte til Norge?',
        characterEnglish: 'That is nice to hear. What would you say to someone who is about to move to Norway?',
        expectedKeywords: ['ville', 'si', 'råd', 'anbefale', 'lære', 'norsk', 'åpen', 'ta', 'seg', 'tid'],
        hint: 'Give advice in a hypothetical frame: "Jeg ville si at..." or "Mitt råd ville være å...".',
        modelAnswer: 'Mitt råd ville være å lære norsk så fort som mulig og å være åpen for den direkte kommunikasjonsstilen.',
        targetConceptId: 'reported-speech-advanced',
        errorTag: 'verb-tense',
      },
    ],
  },
  // Batch 3 deepening (2026-06-28, linguist-reviewed — all turns PASS).
  {
    id: 'b2-medarbeidersamtale',
    title: 'Medarbeidersamtale',
    titleEnglish: 'Performance review',
    setting: "You're in a performance review with your manager.",
    characterName: 'Leder',
    turns: [
      {
        id: 'reflect',
        character: 'Hvordan synes du det siste halvåret har gått?',
        characterEnglish: 'How do you think the last six months have gone?',
        expectedKeywords: ['stort', 'sett', 'selv', 'om', 'krevende', 'utfordrende'],
        hint: 'Bruk dempet register (Stort sett bra, selv om …).',
        modelAnswer: 'Stort sett bra, selv om noen oppgaver har vært krevende.',
        targetConceptId: 'nuanced-register',
        errorTag: 'word-order',
      },
      {
        id: 'improve',
        character: 'Hva mener du vi kan forbedre i teamet?',
        characterEnglish: 'What do you think we can improve in the team?',
        expectedKeywords: ['på', 'den', 'ene', 'siden', 'rutiner', 'kommunikasjon'],
        hint: 'Argumenter balansert (På den ene siden …, på den andre siden …).',
        modelAnswer: 'På den ene siden trenger vi bedre rutiner, på den andre siden mer tid.',
        targetConceptId: 'complex-argumentation',
        errorTag: 'word-order',
      },
      {
        id: 'counterfactual',
        character: 'Hva ville du ha gjort annerledes i prosjektet?',
        characterEnglish: 'What would you have done differently in the project?',
        expectedKeywords: ['ville', 'ha', 'involvert', 'hvis', 'hadde'],
        hint: 'Bruk sammensatt kondisjonalis (Jeg ville ha … hvis jeg hadde …).',
        modelAnswer: 'Jeg ville ha involvert teamet tidligere hvis jeg hadde fått sjansen.',
        targetConceptId: 'advanced-verb-forms',
        errorTag: 'verb-tense',
      },
      {
        id: 'goals',
        character: 'Hva er målene dine framover?',
        characterEnglish: 'What are your goals going forward?',
        expectedKeywords: ['vil', 'ta', 'ansvar', 'utvikle', 'mål', 'faglig'],
        hint: 'Bruk profesjonelt språk (Jeg vil ta mer ansvar og …).',
        modelAnswer: 'Jeg vil ta mer ansvar og utvikle meg faglig.',
        targetConceptId: 'professional-norwegian',
        errorTag: 'word-order',
      },
    ],
  },
  {
    id: 'b2-samfunnstema',
    title: 'Diskutere et samfunnstema',
    titleEnglish: 'Discussing a societal topic',
    setting: 'A friend wants to discuss whether more people working from home is good for society.',
    characterName: 'Venn',
    turns: [
      {
        id: 'opinion',
        character: 'Hva synes du om at flere jobber hjemmefra nå?',
        characterEnglish: 'What do you think about more people working from home now?',
        expectedKeywords: ['både', 'fordeler', 'ulemper', 'synes', 'kommer', 'an'],
        hint: 'Nyansér (Det har både fordeler og ulemper, vil jeg si).',
        modelAnswer: 'Det har både fordeler og ulemper, vil jeg si.',
        targetConceptId: 'nuanced-register',
        errorTag: 'word-order',
      },
      {
        id: 'society',
        character: 'Tror du det er bra for samfunnet?',
        characterEnglish: "Do you think it's good for society?",
        expectedKeywords: ['på', 'den', 'ene', 'siden', 'samtidig', 'derimot'],
        hint: 'Bind argumentene sammen (På den ene siden …, på den andre siden …).',
        modelAnswer: 'På den ene siden sparer folk tid, på den andre siden blir vi mer isolerte.',
        targetConceptId: 'text-cohesion',
        errorTag: 'word-order',
      },
      {
        id: 'research',
        character: 'Hva sier forskningen om det?',
        characterEnglish: 'What does the research say about it?',
        expectedKeywords: ['forskningen', 'tyder', 'på', 'viser', 'at'],
        hint: 'Bruk akademiske formler (Forskningen tyder på at …).',
        modelAnswer: 'Forskningen tyder på at produktiviteten øker, men trivselen varierer.',
        targetConceptId: 'academic-writing',
        errorTag: 'word-order',
      },
      {
        id: 'future',
        character: 'Hva tror du om framtiden?',
        characterEnglish: 'What do you think about the future?',
        expectedKeywords: ['trolig', 'kanskje', 'blir', 'framtiden', 'tror'],
        hint: 'Bruk inversjon ved fronting (Trolig blir hybridarbeid normen).',
        modelAnswer: 'Vanskelig å si, men trolig blir hybridarbeid normen.',
        targetConceptId: 'advanced-word-order',
        errorTag: 'word-order',
      },
    ],
  },
]

// A2 = combination level: each scenario chains 4 turns eliciting perfect tense,
// modals, comparatives, prepositions, reflexives, negation, future, and subordinate
// clauses in a realistic everyday exchange. Linguist-reviewed 2026-06-27 (all 12
// turns PASS; "Jo" negative-question response confirmed correct).
const A2_SCENARIOS: RoleplayScenario[] = [
  {
    id: 'a2-butikk',
    title: 'På butikken',
    titleEnglish: 'At the grocery shop',
    setting: "You're shopping for groceries. The shop assistant offers to help.",
    characterName: 'Butikkmedarbeider',
    turns: [
      {
        id: 'find',
        character: 'Hei! Trenger du hjelp til å finne noe?',
        characterEnglish: 'Hi! Do you need help finding anything?',
        expectedKeywords: ['leter', 'etter', 'trenger', 'hvor', 'har', 'dere'],
        hint: 'Si hva du leter etter (leter etter …).',
        modelAnswer: 'Ja, jeg leter etter brød og melk.',
        targetConceptId: 'advanced-prepositions',
        errorTag: 'preposition',
      },
      {
        id: 'choose',
        character: 'Vi har to typer brød — grovt og fint. Hva foretrekker du?',
        characterEnglish: 'We have two kinds of bread — wholegrain and white. Which do you prefer?',
        expectedKeywords: ['grovt', 'fint', 'foretrekker', 'heller', 'sunnere', 'enn'],
        hint: 'Sammenlign og velg (… er sunnere enn …).',
        modelAnswer: 'Jeg foretrekker grovt brød, det er sunnere.',
        targetConceptId: 'comparative-adjectives',
        errorTag: 'adjective-agreement',
      },
      {
        id: 'amount',
        character: 'Hvor mye vil du ha?',
        characterEnglish: 'How much would you like?',
        expectedKeywords: ['vil', 'ha', 'to', 'liter', 'kilo', 'noen'],
        hint: 'Bruk modalverb + mengde (Jeg vil ha to liter …).',
        modelAnswer: 'Jeg vil ha to liter melk, takk.',
        targetConceptId: 'modal-verbs-advanced',
        errorTag: 'modal-verb',
      },
      {
        id: 'pay',
        character: 'Det blir 95 kroner. Vil du betale med kort?',
        characterEnglish: "That'll be 95 kroner. Would you like to pay by card?",
        expectedKeywords: ['kort', 'kontant', 'betaler', 'med', 'ja'],
        hint: 'Bruk preposisjon (betale med kort).',
        modelAnswer: 'Ja, jeg betaler med kort.',
        targetConceptId: 'advanced-prepositions',
        errorTag: 'preposition',
      },
    ],
  },
  {
    id: 'a2-legen',
    title: 'Hos legen',
    titleEnglish: 'At the doctor',
    setting: "You're at the doctor's office. The doctor asks about your symptoms.",
    characterName: 'Lege',
    turns: [
      {
        id: 'symptom',
        character: 'Hei. Hva kan jeg hjelpe deg med i dag?',
        characterEnglish: 'Hi. What can I help you with today?',
        expectedKeywords: ['føler', 'meg', 'syk', 'vondt', 'har', 'i'],
        hint: 'Bruk refleksivt verb (føler meg …).',
        modelAnswer: 'Jeg føler meg syk og har vondt i hodet.',
        targetConceptId: 'reflexive-verbs',
        errorTag: 'pronoun-choice',
      },
      {
        id: 'duration',
        character: 'Hvor lenge har du følt deg sånn?',
        characterEnglish: 'How long have you felt like this?',
        expectedKeywords: ['har', 'følt', 'i', 'dager', 'siden', 'uke'],
        hint: 'Bruk perfektum (Jeg har følt meg … i tre dager).',
        modelAnswer: 'Jeg har følt meg dårlig i tre dager.',
        targetConceptId: 'perfect-tense',
        errorTag: 'verb-tense',
      },
      {
        id: 'medicine',
        character: 'Tar du noen medisiner nå?',
        characterEnglish: 'Are you taking any medication now?',
        expectedKeywords: ['tar', 'ikke', 'noen', 'bruker', 'nei'],
        hint: "Plasser 'ikke' riktig (Jeg tar ikke noen medisiner).",
        modelAnswer: 'Nei, jeg tar ikke noen medisiner nå.',
        targetConceptId: 'sentence-adverbials',
        errorTag: 'negation-placement',
      },
      {
        id: 'advice',
        character: 'Du bør hvile. Skal jeg skrive ut en resept?',
        characterEnglish: 'You should rest. Shall I write you a prescription?',
        expectedKeywords: ['ja', 'takk', 'gjerne', 'bør', 'trenger'],
        hint: 'Svar med modalverb (Ja takk, det hadde vært fint).',
        modelAnswer: 'Ja takk, det hadde vært fint.',
        targetConceptId: 'modal-verbs-advanced',
        errorTag: 'modal-verb',
      },
    ],
  },
  {
    id: 'a2-nabo',
    title: 'Småprat med en nabo',
    titleEnglish: 'Small talk with a neighbour',
    setting: 'You meet your neighbour in the hallway. They start a conversation.',
    characterName: 'Nabo',
    turns: [
      {
        id: 'weekend',
        character: 'Hei! Hadde du en fin helg?',
        characterEnglish: 'Hi! Did you have a nice weekend?',
        expectedKeywords: ['ja', 'hadde', 'var', 'fin', 'koselig', 'tur'],
        hint: 'Fortell om helga i fortid (Jeg hadde …, jeg var …).',
        modelAnswer: 'Ja, jeg hadde en fin helg. Jeg var på tur.',
        targetConceptId: 'preterite-irregular-advanced',
        errorTag: 'verb-tense',
      },
      {
        id: 'weather',
        character: 'Været er bedre i dag enn i går, synes du ikke?',
        characterEnglish: "The weather is better today than yesterday, don't you think?",
        expectedKeywords: ['jo', 'enig', 'varmere', 'finere', 'enn', 'bedre'],
        hint: "Svar 'Jo' på et negativt spørsmål, og sammenlign (varmere enn).",
        modelAnswer: 'Jo, det er mye varmere i dag.',
        targetConceptId: 'comparative-adjectives',
        errorTag: 'adjective-agreement',
      },
      {
        id: 'summer',
        character: 'Har du noen planer til sommeren?',
        characterEnglish: 'Do you have any plans for the summer?',
        expectedKeywords: ['skal', 'reise', 'til', 'planlegger', 'ferie', 'kommer'],
        hint: 'Snakk om framtid (Jeg skal reise til …).',
        modelAnswer: 'Ja, jeg skal reise til Spania i sommer.',
        targetConceptId: 'future-constructions',
        errorTag: 'verb-tense',
      },
      {
        id: 'offer',
        character: 'Så hyggelig! Si fra hvis du trenger noe.',
        characterEnglish: 'How nice! Let me know if you need anything.',
        expectedKeywords: ['takk', 'det', 'skal', 'jeg', 'gjøre', 'hvis'],
        hint: 'Takk og svar med en leddsetning (… det skal jeg gjøre).',
        modelAnswer: 'Tusen takk, det skal jeg gjøre.',
        targetConceptId: 'subordinate-clauses',
        errorTag: 'word-order',
      },
    ],
  },
]

/** @deprecated use getRoleplayScenarios(level) instead */
export const ROLEPLAY_SCENARIOS: RoleplayScenario[] = A1_SCENARIOS

/**
 * Returns the roleplay scenarios appropriate for the learner's CEFR level.
 * Falls back to A1 scenarios for A2 and unknown levels.
 */
export function getRoleplayScenarios(level: string): RoleplayScenario[] {
  if (level === 'B2') return B2_SCENARIOS
  if (level === 'B1') return B1_SCENARIOS
  if (level === 'A2') return A2_SCENARIOS
  return A1_SCENARIOS
}

/**
 * The CEFR level whose scenarios are ACTUALLY served for a learner level. A1/A2/
 * B1/B2 all have dedicated sets now; only unknown levels fall back to A1. Exposing
 * this lets the UI honestly disclose below-level content instead of substituting
 * silently (Operating Rule 6).
 */
export function getRoleplayContentLevel(level: string): string {
  if (level === 'B2') return 'B2'
  if (level === 'B1') return 'B1'
  if (level === 'A2') return 'A2'
  if (level === 'A1') return 'A1'
  return 'A1' // unknown → A1 scenarios
}
