import type { CEFRLevel } from '@/types/fingerprint'

export interface DiagnosticQuestion {
  id: string
  cefrLevel: CEFRLevel
  conceptId: string
  /** 0.0 easy → 1.0 hard within the level */
  difficulty: number
  prompt: string
  options: string[]
  correctIndex: number
  explanation: string
}

export const DIAGNOSTIC_QUESTIONS: DiagnosticQuestion[] = [
  // ── A1 ─────────────────────────────────────────────────────────────────
  {
    id: 'a1-q1',
    cefrLevel: 'A1',
    conceptId: 'noun-gender',
    difficulty: 0.2,
    prompt: 'Choose the correct indefinite article: "___ hund"',
    options: ['en', 'ei', 'et', 'de'],
    correctIndex: 0,
    explanation: 'Hund (dog) is a masculine noun — it takes "en".',
  },
  {
    id: 'a1-q2',
    cefrLevel: 'A1',
    conceptId: 'noun-gender',
    difficulty: 0.5,
    prompt: 'Choose the correct indefinite article: "___ hus"',
    options: ['en', 'ei', 'et', 'den'],
    correctIndex: 2,
    explanation: 'Hus (house) is a neuter noun — it takes "et".',
  },
  {
    id: 'a1-q3',
    cefrLevel: 'A1',
    conceptId: 'present-tense-regular',
    difficulty: 0.2,
    prompt: 'Fill in: "Jeg ___ norsk." (speak)',
    options: ['snakke', 'snakker', 'snakket', 'snakkes'],
    correctIndex: 1,
    explanation: 'Present tense in Norwegian adds -r to the verb stem: snakk- → snakker.',
  },
  {
    id: 'a1-q4',
    cefrLevel: 'A1',
    conceptId: 'personal-pronouns',
    difficulty: 0.2,
    prompt: 'Translate: "She is a teacher."',
    options: ['Han er en lærer.', 'Hun er en lærer.', 'De er en lærer.', 'Vi er en lærer.'],
    correctIndex: 1,
    explanation: '"She" = hun in Norwegian.',
  },
  {
    id: 'a1-q5',
    cefrLevel: 'A1',
    conceptId: 'svo-word-order',
    difficulty: 0.4,
    prompt: 'Which sentence has the correct word order?',
    options: [
      'Kaffe jeg drikker.',
      'Jeg drikker kaffe.',
      'Drikker kaffe jeg.',
      'Jeg kaffe drikker.',
    ],
    correctIndex: 1,
    explanation: 'Norwegian main clauses follow Subject–Verb–Object order in simple statements.',
  },
  {
    id: 'a1-q6',
    cefrLevel: 'A1',
    conceptId: 'definite-articles-singular',
    difficulty: 0.6,
    prompt: 'Make "et hus" definite (the house):',
    options: ['den hus', 'huset', 'hus-en', 'et huset'],
    correctIndex: 1,
    explanation: 'Neuter nouns (et-words) take the suffix -et in the definite form.',
  },

  // ── A2 ─────────────────────────────────────────────────────────────────
  {
    id: 'a2-q1',
    cefrLevel: 'A2',
    conceptId: 'v2-word-order',
    difficulty: 0.3,
    prompt: 'I morgen ___ jeg til Oslo. (I am going to Oslo tomorrow.)',
    options: ['jeg reiser', 'reiser jeg', 'jeg skal reiser', 'reise jeg'],
    correctIndex: 1,
    explanation: 'V2 rule: when "i morgen" starts the sentence, verb and subject invert.',
  },
  {
    id: 'a2-q2',
    cefrLevel: 'A2',
    conceptId: 'negation',
    difficulty: 0.4,
    prompt: 'Translate: "I do not speak Norwegian."',
    options: [
      'Jeg snakker norsk ikke.',
      'Jeg ikke snakker norsk.',
      'Jeg snakker ikke norsk.',
      'Ikke jeg snakker norsk.',
    ],
    correctIndex: 2,
    explanation: '"Ikke" (not) comes directly after the finite verb in a main clause.',
  },
  {
    id: 'a2-q3',
    cefrLevel: 'A2',
    conceptId: 'preterite-regular',
    difficulty: 0.4,
    prompt: 'Put "å jobbe" (to work) in the past tense: "I går ___ jeg hjemme."',
    options: ['jobber', 'jobbet', 'jobb', 'har jobbet'],
    correctIndex: 1,
    explanation: '"Jobbe" is a weak verb — past tense adds -et: jobbet.',
  },
  {
    id: 'a2-q4',
    cefrLevel: 'A2',
    conceptId: 'adjective-agreement',
    difficulty: 0.5,
    prompt: 'Choose the correct form: "et ___ hus" (big house)',
    options: ['stor', 'store', 'stort', 'stora'],
    correctIndex: 2,
    explanation: 'Adjectives agree with neuter nouns — "stor" → "stort" for et-words.',
  },
  {
    id: 'a2-q5',
    cefrLevel: 'A2',
    conceptId: 'common-modal-verbs',
    difficulty: 0.5,
    prompt: 'Which sentence is correct?',
    options: [
      'Jeg kan å snakke norsk.',
      'Jeg kan snakke norsk.',
      'Jeg kan snakker norsk.',
      'Jeg kanner snakke norsk.',
    ],
    correctIndex: 1,
    explanation: 'Modal verbs (kan, vil, skal, må) are followed by a bare infinitive — no "å".',
  },
  {
    id: 'a2-q6',
    cefrLevel: 'A2',
    conceptId: 'question-formation',
    difficulty: 0.6,
    prompt: 'Form a question: "You speak Norwegian." → "___?"',
    options: [
      'Du snakker norsk?',
      'Snakker du norsk?',
      'Norsk snakker du?',
      'Du snakker norsk ikke?',
    ],
    correctIndex: 1,
    explanation: 'Yes/no questions invert subject and verb: "Snakker du norsk?"',
  },

  // ── B1 ─────────────────────────────────────────────────────────────────
  {
    id: 'b1-q1',
    cefrLevel: 'B1',
    conceptId: 'v2-word-order',
    difficulty: 0.5,
    prompt: 'Which sentence correctly uses V2 in a subordinate clause context?',
    options: [
      'Han sa at han ikke var hjemme.',
      'Han sa at ikke han var hjemme.',
      'Han sa at var han ikke hjemme.',
      'Han sa at han var hjemme ikke.',
    ],
    correctIndex: 0,
    explanation: 'In subordinate clauses (after "at"), "ikke" comes before the verb: "at han ikke var".',
  },
  {
    id: 'b1-q2',
    cefrLevel: 'B1',
    conceptId: 'preterite-regular',
    difficulty: 0.6,
    prompt: 'Choose the correct past tense of "å kjøre" (to drive): "Vi ___ til Bergen i går."',
    options: ['kjørte', 'kjøret', 'kjørte', 'kjørde'],
    correctIndex: 0,
    explanation: '"Kjøre" is a short-stem verb that takes -te in the past: kjørte.',
  },
  {
    id: 'b1-q3',
    cefrLevel: 'B1',
    conceptId: 'adjective-agreement',
    difficulty: 0.65,
    prompt: 'Fill in: "Den ___ bilen er ny." (big car)',
    options: ['stor', 'store', 'stort', 'storeste'],
    correctIndex: 1,
    explanation: 'Definite nouns take the definite adjective form "store" regardless of gender.',
  },
  {
    id: 'b1-q4',
    cefrLevel: 'B1',
    conceptId: 'common-prepositions',
    difficulty: 0.6,
    prompt: 'Complete: "Jeg bor ___ Oslo." (I live in Oslo.)',
    options: ['på', 'i', 'til', 'fra'],
    correctIndex: 1,
    explanation: '"I" is used for being inside a country, city, or enclosed space: "bor i Oslo".',
  },
  {
    id: 'b1-q5',
    cefrLevel: 'B1',
    conceptId: 'common-modal-verbs',
    difficulty: 0.7,
    prompt: '"Du ___ gjøre det." means "You must do it." Which modal is correct?',
    options: ['kan', 'vil', 'skal', 'må'],
    correctIndex: 3,
    explanation: '"Må" expresses obligation or necessity — equivalent to "must".',
  },
  {
    id: 'b1-q6',
    cefrLevel: 'B1',
    conceptId: 'negation',
    difficulty: 0.75,
    prompt: 'Translate: "I know that she does not live here."',
    options: [
      'Jeg vet at hun ikke bor her.',
      'Jeg vet at hun bor ikke her.',
      'Jeg vet ikke at hun bor her.',
      'Jeg ikke vet at hun bor her.',
    ],
    correctIndex: 0,
    explanation: 'In subordinate clauses, "ikke" comes before the main verb: "at hun ikke bor".',
  },

  // ── B2 ─────────────────────────────────────────────────────────────────
  {
    id: 'b2-q1',
    cefrLevel: 'B2',
    conceptId: 'v2-word-order',
    difficulty: 0.8,
    prompt: 'Which option correctly uses inversion after an adverbial clause?',
    options: [
      'Selv om det regner, jeg går ut.',
      'Selv om det regner, går jeg ut.',
      'Selv om regner det, jeg går ut.',
      'Selv om det regner, jeg ut går.',
    ],
    correctIndex: 1,
    explanation: 'After an adverbial clause, the main clause still requires V2: "går jeg".',
  },
  {
    id: 'b2-q2',
    cefrLevel: 'B2',
    conceptId: 'preterite-regular',
    difficulty: 0.8,
    prompt: 'Which sentence uses the present perfect correctly?',
    options: [
      'Jeg har spist allerede.',
      'Jeg hadde spist allerede.',
      'Jeg spiste allerede.',
      'Jeg har spise allerede.',
    ],
    correctIndex: 0,
    explanation: 'Present perfect: "har" + past participle. "Spise" → "spist": "har spist".',
  },
  {
    id: 'b2-q3',
    cefrLevel: 'B2',
    conceptId: 'adjective-agreement',
    difficulty: 0.85,
    prompt: 'Choose the correct superlative form: "Dette er den ___ boken." (most interesting)',
    options: ['interessant', 'interessante', 'interessanteste', 'mest interessante'],
    correctIndex: 3,
    explanation: 'Long adjectives form superlatives with "mest + adjective": "mest interessante".',
  },
  {
    id: 'b2-q4',
    cefrLevel: 'B2',
    conceptId: 'negation',
    difficulty: 0.85,
    prompt: 'Translate: "I doubt that he has not been honest."',
    options: [
      'Jeg tviler på at han ikke har vært ærlig.',
      'Jeg tviler ikke at han har vært ærlig.',
      'Jeg tviler på at han har ikke vært ærlig.',
      'Jeg ikke tviler på at han ikke har vært ærlig.',
    ],
    correctIndex: 0,
    explanation: 'In the subordinate clause after "at", "ikke" precedes the auxiliary: "ikke har vært".',
  },
  {
    id: 'b2-q5',
    cefrLevel: 'B2',
    conceptId: 'common-modal-verbs',
    difficulty: 0.8,
    prompt: '"Han ___ ha gjort det." — which modal fits "must have done"?',
    options: ['kan', 'skal', 'må', 'vil'],
    correctIndex: 2,
    explanation: '"Må ha gjort" = "must have done" — logical necessity in the past.',
  },
  {
    id: 'b2-q6',
    cefrLevel: 'B2',
    conceptId: 'v2-word-order',
    difficulty: 0.9,
    prompt: 'Which sentence is grammatically correct?',
    options: [
      'Hadde jeg visst det, ville jeg ha kommet.',
      'Hvis jeg visst hadde det, vil jeg komme.',
      'Hadde jeg visst det, jeg ville ha kommet.',
      'Jeg hadde visst det, ville ha kommet.',
    ],
    correctIndex: 0,
    explanation: 'Inverted conditional: "Hadde jeg visst" → "ville jeg ha kommet". Both clauses use V2.',
  },
]
