/**
 * build-verb-forms.ts — generate src/lib/verb-forms.ts (deterministic verb paradigms).
 *
 * Emits VERB_PARADIGMS: lemma -> [present, preterite, perfectParticiple] for common
 * Norwegian Bokmål verbs, used by src/lib/conjugation-verifier.ts to deterministically
 * verify an AI's verb-conjugation correction: confirm only when both words are forms of
 * the SAME verb lemma at different tense slots AND a sentence tense-marker matches the
 * corrected form's tense (and not the original's). Mirrors build-gender-map.ts /
 * build-pos-map.ts (Norsk-ordbank CC-BY, freq∪corpus filter, Latin-1, lemma-base filter).
 *
 * ordbank verb TAG tokens (2nd token after "verb"): pres | pret | perf-part | inf | imp.
 *
 * Run:  npx tsx scripts/build-verb-forms.ts   (commit the regenerated src/lib/verb-forms.ts)
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { resolve } from 'node:path'

const TMP = resolve('.tmp/ordbank')
const FULLFORM = resolve(TMP, 'fullformsliste.txt')
const LEMMA = resolve(TMP, 'lemma.txt')
const FREQ = resolve(TMP, 'nb_freq.txt')
const CORPUS = ['a1', 'a2', 'b1', 'b2'].map((l) => resolve('content/sentences', `${l}.json`))
const OUT = resolve('src/lib/verb-forms.ts')
const FREQ_CUTOFF = 15_000

function tenseSlot(tag: string): number {
  // returns index into [pres, pret, perf] or -1 (inf/imp/other not stored)
  const t = tag.split(/\s+/) // ["verb","pres",...]
  if (t[0] !== 'verb') return -1
  if (t[1] === 'pres') return 0
  if (t[1] === 'pret') return 1
  if (t[1] === 'perf-part') return 2
  return -1
}

function ensureSources(): void {
  if (!existsSync(TMP)) mkdirSync(TMP, { recursive: true })
  if (!existsSync(FULLFORM)) {
    execSync(
      `curl -sL -o "${TMP}/ob.tar.gz" https://www.nb.no/sbfil/leksikalske_databaser/ordbank/20220201_norsk_ordbank_nob_2005.tar.gz && tar -xzf "${TMP}/ob.tar.gz" -C "${TMP}"`,
      { stdio: 'inherit', shell: '/bin/bash' },
    )
  }
  if (!existsSync(FREQ)) {
    execSync(
      `curl -sL -o "${FREQ}" https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2016/no/no_50k.txt`,
      { stdio: 'inherit', shell: '/bin/bash' },
    )
  }
}

function main(): void {
  ensureSources()

  // Frequency-allowed lemma base forms (drops rare homograph verb lemmas).
  const allowedBase = new Set<string>()
  const freqWords = readFileSync(FREQ, 'utf8').split('\n').map((l) => l.split(' ')[0]).filter(Boolean)
  for (let i = 0; i < Math.min(FREQ_CUTOFF, freqWords.length); i++) allowedBase.add(freqWords[i])
  for (const file of CORPUS) {
    const parsed = JSON.parse(readFileSync(file, 'utf8'))
    const list: Array<{ norwegian?: string; notes?: string }> = Array.isArray(parsed) ? parsed : (Object.values(parsed)[0] as [])
    for (const s of list) {
      for (const w of (s.norwegian ?? '').toLowerCase().split(/[^a-zæøå]+/)) if (w) allowedBase.add(w)
      for (const w of (s.notes ?? '').toLowerCase().split(/[^a-zæøå]+/)) if (w) allowedBase.add(w)
    }
  }

  // lemma.txt: col 1 LEMMA_ID | col 2 GRUNNFORM (base form).
  const lemmaBase = new Map<string, string>()
  for (const line of readFileSync(LEMMA, 'latin1').split('\n')) {
    if (!line) continue
    const c = line.split('\t')
    if (c.length < 3 || !/^\d+$/.test(c[0])) continue
    lemmaBase.set(c[1], c[2].toLowerCase().trim())
  }

  // Collect per-lemma tense forms. paradigm[base] = [presSet, pretSet, perfSet]
  const paradigm = new Map<string, [Set<string>, Set<string>, Set<string>]>()
  for (const line of readFileSync(FULLFORM, 'latin1').split('\n')) {
    if (!line) continue
    const c = line.split('\t')
    if (c.length < 4 || !/^\d+$/.test(c[0])) continue
    const slot = tenseSlot(c[3])
    if (slot < 0) continue
    const base = lemmaBase.get(c[1])
    if (!base || !allowedBase.has(base)) continue
    const form = c[2].toLowerCase().trim()
    if (!form || form.includes(' ') || !/^[a-zæøå]+$/.test(form)) continue
    if (!paradigm.has(base)) paradigm.set(base, [new Set(), new Set(), new Set()])
    paradigm.get(base)![slot].add(form)
  }

  // Emit lemma -> [pres, pret, perf] (join multiple forms with '|'; keep only lemmas
  // that have at least a present AND a preterite — the minimum to verify a tense swap).
  const map: Record<string, [string, string, string]> = {}
  for (const [base, [pres, pret, perf]] of paradigm) {
    if (pres.size === 0 || pret.size === 0) continue
    map[base] = [[...pres].sort().join('|'), [...pret].sort().join('|'), [...perf].sort().join('|')]
  }
  const sorted: Record<string, [string, string, string]> = {}
  for (const k of Object.keys(map).sort()) sorted[k] = map[k]

  const out = `// AUTO-GENERATED by scripts/build-verb-forms.ts — DO NOT EDIT BY HAND.
// Regenerate: npx tsx scripts/build-verb-forms.ts
//
// Source: Norsk ordbank – bokmål 2005, Språkrådet/Nasjonalbiblioteket, CC-BY 4.0
//   https://www.nb.no/sprakbanken/en/resource-catalogue/oai-nb-no-sbr-5/
// Coverage: top-${FREQ_CUTOFF.toLocaleString('en')} OpenSubtitles-frequency forms ∪ app corpus.
// Verbs outside this set are intentionally ABSENT — conjugation-verifier treats an
// unknown verb as not-applicable and never moves mastery (OOV-safe by design).
//
// Value = [present, preterite, perfectParticiple]; each slot is '|'-joined when a
// lemma has multiple accepted forms. Only lemmas with both a present and a preterite
// are kept (the minimum to verify a tense swap).
//
// ${Object.keys(sorted).length} verb lemmas.
export const VERB_PARADIGMS: Record<string, [string, string, string]> = ${JSON.stringify(sorted)}
`
  writeFileSync(OUT, out)
  console.log(`[build-verb-forms] wrote ${OUT} (${Object.keys(sorted).length} lemmas)`)
}

main()
