/**
 * build-adj-forms.ts — generate src/lib/adj-forms.ts (deterministic adjective paradigms).
 *
 * Emits ADJ_PARADIGMS: lemma -> [common, neuter, pluralDefinite] for common Norwegian
 * Bokmål positive-degree adjectives, used by src/lib/adjective-verifier.ts to verify an
 * AI adjective-agreement correction: the determiner before the adjective fixes the
 * required form (en→common, et→neuter+t, den/de/mange→+e).
 *
 * Mirrors build-verb-forms.ts (Norsk-ordbank CC-BY, freq∪corpus + lemma-base filter,
 * Latin-1). ordbank positive-adjective TAG tokens after "adj pos":
 *   m/f ub ent → common base | nøyt ub ent → neuter (+t) | fl OR be ent → plural/definite (+e)
 *
 * Run:  npx tsx scripts/build-adj-forms.ts   (commit the regenerated src/lib/adj-forms.ts)
 */
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { execSync } from 'node:child_process'
import { resolve } from 'node:path'

const TMP = resolve('.tmp/ordbank')
const FULLFORM = resolve(TMP, 'fullformsliste.txt')
const LEMMA = resolve(TMP, 'lemma.txt')
const FREQ = resolve(TMP, 'nb_freq.txt')
const CORPUS = ['a1', 'a2', 'b1', 'b2'].map((l) => resolve('content/sentences', `${l}.json`))
const OUT = resolve('src/lib/adj-forms.ts')
const FREQ_CUTOFF = 15_000

// returns slot index into [common, neuter, pluralDefinite], or -1.
function adjSlot(tag: string): number {
  if (!tag.startsWith('adj pos')) return -1 // positive degree only (skip sup/participial)
  if (tag.includes('fl') || (tag.includes(' be ') && tag.includes('ent'))) return 2 // plural or definite-sg → +e
  if (tag.includes('nøyt') && tag.includes('ub') && tag.includes('ent')) return 1 // neuter sg indef → +t
  if ((tag.includes('m/f') || tag.includes('mask') || tag.includes('fem')) && tag.includes('ub') && tag.includes('ent')) return 0
  return -1
}

function ensureSources(): void {
  if (!existsSync(TMP)) mkdirSync(TMP, { recursive: true })
  if (!existsSync(FULLFORM)) {
    execSync(`curl -sL -o "${TMP}/ob.tar.gz" https://www.nb.no/sbfil/leksikalske_databaser/ordbank/20220201_norsk_ordbank_nob_2005.tar.gz && tar -xzf "${TMP}/ob.tar.gz" -C "${TMP}"`, { stdio: 'inherit', shell: '/bin/bash' })
  }
  if (!existsSync(FREQ)) {
    execSync(`curl -sL -o "${FREQ}" https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2016/no/no_50k.txt`, { stdio: 'inherit', shell: '/bin/bash' })
  }
}

function main(): void {
  ensureSources()

  const allowedBase = new Set<string>()
  const freqWords = readFileSync(FREQ, 'utf8').split('\n').map((l) => l.split(' ')[0]).filter(Boolean)
  for (let i = 0; i < Math.min(FREQ_CUTOFF, freqWords.length); i++) allowedBase.add(freqWords[i])
  for (const file of CORPUS) {
    const parsed = JSON.parse(readFileSync(file, 'utf8'))
    const list: Array<{ norwegian?: string; notes?: string }> = Array.isArray(parsed) ? parsed : (Object.values(parsed)[0] as [])
    for (const s of list) {
      for (const w of (s.norwegian ?? '').toLowerCase().split(/[^a-zæøå]+/)) if (w) allowedBase.add(w)
      for (const w of (s.notes ?? '').toLowerCase().split(/[^a-zæøå]+/)) if (w) allowedBase.add(w)
    }
  }

  const lemmaBase = new Map<string, string>()
  for (const line of readFileSync(LEMMA, 'latin1').split('\n')) {
    if (!line) continue
    const c = line.split('\t')
    if (c.length < 3 || !/^\d+$/.test(c[0])) continue
    lemmaBase.set(c[1], c[2].toLowerCase().trim())
  }

  const paradigm = new Map<string, [Set<string>, Set<string>, Set<string>]>()
  for (const line of readFileSync(FULLFORM, 'latin1').split('\n')) {
    if (!line) continue
    const c = line.split('\t')
    if (c.length < 4 || !/^\d+$/.test(c[0])) continue
    const slot = adjSlot(c[3])
    if (slot < 0) continue
    const base = lemmaBase.get(c[1])
    if (!base || !allowedBase.has(base)) continue
    const form = c[2].toLowerCase().trim()
    if (!form || form.includes(' ') || !/^[a-zæøå]+$/.test(form)) continue
    if (!paradigm.has(base)) paradigm.set(base, [new Set(), new Set(), new Set()])
    paradigm.get(base)![slot].add(form)
  }

  // Keep lemmas that have at least a common form (the agreement anchor).
  const map: Record<string, [string, string, string]> = {}
  for (const [base, [common, neuter, plurdef]] of paradigm) {
    if (common.size === 0) continue
    map[base] = [[...common].sort().join('|'), [...neuter].sort().join('|'), [...plurdef].sort().join('|')]
  }
  const sorted: Record<string, [string, string, string]> = {}
  for (const k of Object.keys(map).sort()) sorted[k] = map[k]

  const out = `// AUTO-GENERATED by scripts/build-adj-forms.ts — DO NOT EDIT BY HAND.
// Regenerate: npx tsx scripts/build-adj-forms.ts
//
// Source: Norsk ordbank – bokmål 2005, Språkrådet/Nasjonalbiblioteket, CC-BY 4.0
//   https://www.nb.no/sprakbanken/en/resource-catalogue/oai-nb-no-sbr-5/
// Coverage: top-${FREQ_CUTOFF.toLocaleString('en')} OpenSubtitles-frequency forms ∪ app corpus.
// Adjectives outside this set are intentionally ABSENT — adjective-verifier treats an
// unknown adjective as not-applicable and never moves mastery (OOV-safe by design).
//
// Value = [common, neuter, pluralDefinite]; each slot '|'-joined when a lemma has
// multiple forms. common = en/ei singular indefinite (base); neuter = et singular
// indefinite (+t); pluralDefinite = plural OR definite (+e). Only positive-degree
// adjectives with at least a common form are kept.
//
// ${Object.keys(sorted).length} adjective lemmas.
export const ADJ_PARADIGMS: Record<string, [string, string, string]> = ${JSON.stringify(sorted)}
`
  writeFileSync(OUT, out)
  console.log(`[build-adj-forms] wrote ${OUT} (${Object.keys(sorted).length} lemmas)`)
}

main()
